-- 1

CREATE PROCEDURE RETURNHELLO()
BEGIN
	IF (CURRENT_TIMESTAMP >= '06:00:00' AND CURRENT_TIMESTAMP <= '12:00:00') THEN SELECT 'GOOD MORNING';
	ELSE IF
		(CURRENT_TIMESTAMP >= '12:00:01' AND CURRENT_TIMESTAMP <= '18:00:00') THEN SELECT 'GOOD DAY';
	ELSE IF
		(CURRENT_TIMESTAMP >= '18:00:01' AND CURRENT_TIMESTAMP <= '23:59:59') THEN SELECT 'GOOD EVENING';
	ELSE SELECT 'GOOD NIGHT'
	END IF;
END

-- 2

CREATE TRIGGER check_product_null BEFORE INSERT ON products
FOR EACH ROW BEGIN
 IF (NEW.name IS NULL AND NEW.description IS NULL) THEN 
 SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'INSERT RESTRICTED';
 END IF;
END

CREATE TRIGGER check_product_null BEFORE UPDATE ON products
FOR EACH ROW BEGIN
 IF (NEW.name IS NULL AND NEW.description IS NULL) THEN 
 SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'INSERT RESTRICTED';
 END IF;
END

-- 3

CREATE PROCEDURE fibbonaci_number(n INT,OUT outputF INT)
BEGIN
  DECLARE n_1 INT;
  DECLARE n_2 INT;

  IF (n=0) THEN
    SET outputF=0;
  ELSEIF (n=1) then
    SET outputF=1;
  ELSE
    CALL fibbonaci_number(n-1,n_1);
    CALL fibbonaci_number(n-2,n_2);
    SET outputF=(n_1 + n_2);
  END IF;
END